0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,1.00e+00,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,0.00e+00,nan,nan,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,0.00e+00,nan,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,nan,1.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,3.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,0.00e+00,0.00e+00,7.00e+00   
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,0.00e+00,8.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,1.00e+00,3.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00,5.00e+00  
0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,0.00e+00,1.00e+00

δ_WANN= sin⁡(θ_10 π)+sin⁡((θ_2  - θ_3 )π)+tanh⁡〖(θ_1+θ_2+θ_7+|θ_9 |+θ_10 +θ_11+sin⁡((θ_2 - θ_3 )π) 〗⁡  
Reward=1/((1+Loss))

In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm as tqdm
import matplotlib.pyplot as plt
import os

In [2]:
task_course1 = pd.read_pickle('~/デスクトップ/浮田_WANN/WANNRelease/WANN/UkitaSim/kouno_1_test.pickle')
task_course2 = pd.read_pickle('~/デスクトップ/浮田_WANN/WANNRelease/WANN/UkitaSim/kouno_2_test.pickle')
task_course3 = pd.read_pickle('~/デスクトップ/浮田_WANN/WANNRelease/WANN/UkitaSim/kouno_3_test.pickle')
task_course4 = pd.read_pickle('~/デスクトップ/浮田_WANN/WANNRelease/WANN/UkitaSim/kouno_4_test.pickle')


task_course = pd.concat([task_course1, task_course2, task_course3, task_course4], ignore_index=True)
#task_course = task_course1
course_len = len(task_course)

In [3]:
task_course.head()

,Time,X_coordinate,Y_coordinate,Vehicle_angle,Yaw_rate,Steering_angle,Lateral_deviation,gaze_point_x_4.167m,gaze_point_y_4.167m,gaze_kyori_4.167m,...,Lateral_deviation_16.667m,Tangent_slope_theta_16.667m,current_angle_error_16.667m,splay_point_R_x_16.667m,splay_point_R_y_16.667m,splay_point_L_x_16.667m,splay_point_L_y_16.667m,splay_angle_R_16.667m,splay_angle_L_16.667m,splay_error_16.667m
0,0.000000,0.0,0.0,0.0,0.0,0.0,0.02996,4.164612,0.002471,4.164613,...,0.009036,-0.004345,0.004345,16.652909,-1.509022,16.665945,1.490949,0.090369,0.089223,0.001146
1,0.025249,0.0,0.0,0.0,0.0,0.0,0.02996,4.164612,0.002471,4.164613,...,0.009036,-0.004345,0.004345,16.652909,-1.509022,16.665945,1.490949,0.090369,0.089223,0.001146
2,0.083208,0.0,0.0,0.0,0.0,0.0,0.02996,4.164612,0.002471,4.164613,...,0.009036,-0.004345,0.004345,16.652909,-1.509022,16.665945,1.490949,0.090369,0.089223,0.001146
3,0.083491,0.0,0.0,0.0,0.0,0.0,0.02996,4.164612,0.002471,4.164613,...,0.009036,-0.004345,0.004345,16.652909,-1.509022,16.665945,1.490949,0.090369,0.089223,0.001146
4,0.089902,0.0,0.0,0.0,0.0,0.0,0.02996,4.164612,0.002471,4.164613,...,0.009036,-0.004345,0.004345,16.652909,-1.509022,16.665945,1.490949,0.090369,0.089223,0.001146

In [4]:
rad1_df = task_course['visual_angle_4.167m']
rad2_df = task_course['visual_angle_5.417m']
rad3_df = task_course['visual_angle_6.667m']
rad4_df = task_course['visual_angle_7.917m']
rad5_df = task_course['visual_angle_9.167m']
rad6_df = task_course['visual_angle_10.417m']
rad7_df = task_course['visual_angle_11.667m']
rad8_df = task_course['visual_angle_12.917m']
rad9_df = task_course['visual_angle_14.167m']
rad10_df = task_course['visual_angle_15.417m']
rad11_df = task_course['visual_angle_16.667m']

#model_input = np.array([rad1_df,rad2_df,rad3_df,rad4_df,rad5_df,rad6_df,rad7_df,rad8_df,rad9_df,rad10_df,rad11_df])

In [5]:
rad1_df

0       -0.000593
1       -0.000593
2       -0.000593
3       -0.000593
4       -0.000593
           ...
42879    0.339523
42880    0.340193
42881    0.340839
42882    0.342237
42883    0.342847
Name: visual_angle_4.167m, Length: 42884, dtype: float64